### ISSUE TITLE
Solus doesnt open

### ISSUE THREAD

**Issue by ShinigamiH4ck3r** [flathub/com.googleplaymusicdesktopplayer.GPMDP#8] opened 2018-05-09 21:55 UTC
trying to use on solus, doesnt open. output below

> Gtk-Message: Failed to load module "atk-bridge"
> Gtk-Message: Failed to load module "canberra-gtk-module"
> [3:0509/175238.357406:FATAL:process_singleton_posix.cc(226)] Check failed: path.length() < arraysize(addr->sun_path). Socket path too long: /home/shinigamih4ck3r/.var/app/com.googleplaymusicdesktopplayer.GPMDP/cache/.org.chromium.Chromium.yKtOGQ/SS
> #0 0x000003687cc7 <unknown>
> #1 0x00000369bd7b <unknown>
> #2 0x000003f87d16 <unknown>
> #3 0x000003f85ea6 ProcessSingleton::NotifyOtherProcessWithTimeout()
> #4 0x000003f86f91 ProcessSingleton::NotifyOtherProcessWithTimeoutOrCreate()
> #5 0x000003f86f58 ProcessSingleton::NotifyOtherProcessOrCreate()
> #6 0x000003e970af atom::api::App::MakeSingleInstance()
> #7 0x000003ea3d8f _ZN4mate8internal7InvokerINS0_13IndicesHolderIJLm0ELm1EEEEJPN4atom3api3AppERKN4base8CallbackIFbRKSt6vectorISsSaISsEERKNS8_8FilePathEELNS8_8internal8CopyModeE1ELNSJ_10RepeatModeE1EEEEE18DispatchToCallbackIbEEvNS9_IFT_S7_SO_ELSK_1ELSL_1EEE
> #8 0x000003ea3ca1 mate::internal::Dispatcher<>::DispatchToCallback()
> #9 0x7f5a91a95df9 <unknown>
> #10 0x7f5a91efe9c3 <unknown>
> #11 0x7f5a91efdf2e <unknown>
> #12 0x00404678437d <unknown>
>

**Comment by nedrichards** [comment] 2018-05-09 22:02
Duplicate of #1

**Closed as completed by nedrichards** 2018-05-09 22:02 UTC
