### ISSUE TITLE
 Needs a screenshot

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.googleplaymusicdesktopplayer.GPMDP#4] opened 2018-02-04 01:11 UTC
This app needs one or more screenshots added to the appdata, otherwise it looks a bit rubbish in software stores.

**Comment by LeandroStanger** [comment] 2018-02-04 01:11
@nedrichards could help

**Comment by nedrichards** [comment] 2018-02-06 15:08
duplicate of #2

**Closed as completed by nedrichards** 2018-02-06 15:08 UTC
